# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepoFetcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # networking
  pod 'Alamofire', '~> 4.8.0'
  pod 'Moya/RxSwift', '~> 13.0.0'
  pod 'Kingfisher', '5.4.0'

  target 'RepoFetcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
